[package]
name = "chronology"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
rocket = { git = "https://github.com/SergioBenitez/Rocket", features = [ "json" ] }
serde = { version = "1.0", features = ["derive"] }
# sqlx = { version = "0.5", features = [ "chrono","mysql", "runtime-async-std-native-tls" ] }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls","mysql" ] }
tokio = { version = "1.0", features = [ "full" ] }