[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# socket.io-server-rust
# socket_io_server_ = "https://github.com/oguzbilgener/socket.io-server-rust"

