

## set only when compiled in release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[default]
port = 8003
secret_key = ""

[global.databases]
sqlite_logs = { url = "./db.sqlite" }