CREATE TABLE users (
	"id" INT8 NOT NULL GENERATED ALWAYS AS IDENTITY,
	"name" VARCHAR ( 255 ) NOT NULL,
	"password" VARCHAR ( 255 ) NOT NULL,
	"intro" VARCHAR ( 255 ) NOT NULL,
   PRIMARY KEY ( "id" ) 
);